2024-03-07 17:09:03,946 INFO    MainThread:2052 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-03-07 17:09:03,946 INFO    MainThread:2052 [wandb_setup.py:_flush():76] Configure stats pid to 2052
2024-03-07 17:09:03,946 INFO    MainThread:2052 [wandb_setup.py:_flush():76] Loading settings from C:\Users\sebja\.config\wandb\settings
2024-03-07 17:09:03,946 INFO    MainThread:2052 [wandb_setup.py:_flush():76] Loading settings from C:\Users\sebja\Dropbox\github\offset-credits-rl\multi-agent\wandb\settings
2024-03-07 17:09:03,946 INFO    MainThread:2052 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-07 17:09:03,962 INFO    MainThread:2052 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'multi-agent\\main_ddpg.py', 'program_abspath': 'c:\\users\\sebja\\dropbox\\github\\offset-credits-rl\\multi-agent\\main_ddpg.py', 'program': 'c:\\users\\sebja\\dropbox\\github\\offset-credits-rl\\multi-agent\\main_ddpg.py'}
2024-03-07 17:09:03,964 INFO    MainThread:2052 [wandb_init.py:_log_setup():526] Logging user logs to C:\Users\sebja\Dropbox\github\offset-credits-rl\multi-agent\wandb\run-20240307_170903-w8m7ew1m\logs\debug.log
2024-03-07 17:09:03,964 INFO    MainThread:2052 [wandb_init.py:_log_setup():527] Logging internal logs to C:\Users\sebja\Dropbox\github\offset-credits-rl\multi-agent\wandb\run-20240307_170903-w8m7ew1m\logs\debug-internal.log
2024-03-07 17:09:03,964 INFO    MainThread:2052 [wandb_init.py:init():566] calling init triggers
2024-03-07 17:09:03,964 INFO    MainThread:2052 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'random_seed': 3005, 'learning_rate': 0.001, 'gamma': 1, 'tau': 0.001, 'sched_step_size': 50, 'n_nodes': 200, 'n_layers': 5, 'epoch_scale': 200, 'Q_epochs': 5, 'pi_epochs': 1, 'batch_size': 128, 'n_plots': 50000, 'T': 0.08333333333333333, 'S0': 2.5, 'sigma': 0.5, 'kappa': 0.03, 'eta': 0.05, 'xi': 0.1, 'c': 0.25, 'R': 5, 'pen': 2.5}
2024-03-07 17:09:03,964 INFO    MainThread:2052 [wandb_init.py:init():616] starting backend
2024-03-07 17:09:03,964 INFO    MainThread:2052 [wandb_init.py:init():620] setting up manager
2024-03-07 17:09:03,978 INFO    MainThread:2052 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-07 17:09:03,978 INFO    MainThread:2052 [wandb_init.py:init():628] backend started and connected
2024-03-07 17:09:03,994 INFO    MainThread:2052 [wandb_init.py:init():720] updated telemetry
2024-03-07 17:09:04,044 INFO    MainThread:2052 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-07 17:09:04,251 ERROR   MainThread:2052 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-03-07 17:09:04,341 ERROR   MainThread:2052 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "C:\Users\sebja\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
  File "C:\Users\sebja\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-03-07 17:09:38,256 INFO    MainThread:2052 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-03-07 17:09:38,256 INFO    MainThread:2052 [wandb_setup.py:_flush():76] Configure stats pid to 2052
2024-03-07 17:09:38,256 INFO    MainThread:2052 [wandb_setup.py:_flush():76] Loading settings from C:\Users\sebja\.config\wandb\settings
2024-03-07 17:09:38,256 INFO    MainThread:2052 [wandb_setup.py:_flush():76] Loading settings from C:\Users\sebja\Dropbox\github\offset-credits-rl\multi-agent\wandb\settings
2024-03-07 17:09:38,256 INFO    MainThread:2052 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-07 17:09:38,256 INFO    MainThread:2052 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'multi-agent\\main_ddpg.py', 'program_abspath': 'c:\\users\\sebja\\dropbox\\github\\offset-credits-rl\\multi-agent\\main_ddpg.py', 'program': 'c:\\users\\sebja\\dropbox\\github\\offset-credits-rl\\multi-agent\\main_ddpg.py'}
2024-03-07 17:09:38,256 INFO    MainThread:2052 [wandb_init.py:_log_setup():526] Logging user logs to C:\Users\sebja\Dropbox\github\offset-credits-rl\multi-agent\wandb\run-20240307_170938-ia792nal\logs\debug.log
2024-03-07 17:09:38,256 INFO    MainThread:2052 [wandb_init.py:_log_setup():527] Logging internal logs to C:\Users\sebja\Dropbox\github\offset-credits-rl\multi-agent\wandb\run-20240307_170938-ia792nal\logs\debug-internal.log
2024-03-07 17:09:38,256 INFO    MainThread:2052 [wandb_init.py:init():566] calling init triggers
2024-03-07 17:09:38,256 INFO    MainThread:2052 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'random_seed': 3005, 'learning_rate': 0.001, 'gamma': 1, 'tau': 0.001, 'sched_step_size': 50, 'n_nodes': 200, 'n_layers': 5, 'epoch_scale': 200, 'Q_epochs': 5, 'pi_epochs': 1, 'batch_size': 128, 'n_plots': 50000, 'T': 0.08333333333333333, 'S0': 2.5, 'sigma': 0.5, 'kappa': 0.03, 'eta': 0.05, 'xi': 0.1, 'c': 0.25, 'R': 5, 'pen': 2.5}
2024-03-07 17:09:38,256 INFO    MainThread:2052 [wandb_init.py:init():616] starting backend
2024-03-07 17:09:38,256 INFO    MainThread:2052 [wandb_init.py:init():620] setting up manager
2024-03-07 17:09:38,256 INFO    MainThread:2052 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-07 17:09:38,256 INFO    MainThread:2052 [wandb_init.py:init():628] backend started and connected
2024-03-07 17:09:38,273 INFO    MainThread:2052 [wandb_init.py:init():720] updated telemetry
2024-03-07 17:09:38,319 INFO    MainThread:2052 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-07 17:09:42,370 WARNING MainThread:2052 [wandb_init.py:init():1198] interrupted
Traceback (most recent call last):
  File "C:\Users\sebja\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
  File "C:\Users\sebja\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 756, in init
    result = run_init_handle.wait(
  File "C:\Users\sebja\anaconda3\lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "C:\Users\sebja\anaconda3\lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "C:\Users\sebja\anaconda3\lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "C:\Users\sebja\anaconda3\lib\threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Users\sebja\anaconda3\lib\threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-03-07 17:09:42,598 WARNING MsgRouterThr:2052 [router.py:message_loop():77] message_loop has been closed
2024-03-07 17:09:42,598 WARNING MsgRouterThr:2052 [router.py:message_loop():77] message_loop has been closed
